name: profuturistic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.1.1
  flutter: 
    sdk: flutter
  youtube_player_flutter: ^8.1.2
  razorpay_flutter: ^1.3.5
  flutter_zoom_sdk: ^1.1.0+4

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

